baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Tony Abboud"
theme = "base"

[params]
  # description = "Engineer + Tinkerer"
  # description = "Whatever the mind of man can conceive and believe, it can achieve."
  description = "Hello World! I am an Engineer & Tinkerer"
  mainIcon = ""
  githubName = "tdabboud"
  twitterName = "tdabboud"
  linkedinName = "tabboud"
  youtubeName = "tdabboud"

[[params.social]]
    title = "github"
    url = "https://github.com/tdabboud"
[[params.social]]
    title = "youtube"
    url = "https://youtube.com/tdabboud"
[[params.social]]
    title = "linkedin"
    url = "https://linkedin.com/in/tabboud"
